name: qr_qode
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  animated_notch_bottom_bar: ^0.0.6
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_login: ^4.1.1
  get: 4.6.5
  open_file: ^3.2.1
  path_provider: ^2.0.14
  pdf: ^3.3.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
